### ISSUE TITLE
No categories in dropdown

### ISSUE THREAD

**Issue by flytomek** [aune-io/magento2-product-grid-category-filter#6]
Environment:

- OS: Debian GNU/Linux 9
- Magento 2.3.0

Issue:

I can't select a category. Module doesn't see my categories.

<img width="200" alt="screenshot 2019-02-03 at 16 06 36" src="https://user-images.githubusercontent.com/37069663/52178371-fee96b80-27cd-11e9-89a9-efa6417d2bef.png">
<img width="348" alt="screenshot 2019-02-03 at 16 06 21" src="https://user-images.githubusercontent.com/37069663/52178372-fee96b80-27cd-11e9-9f2e-9e4e0bbfa993.png">

**Comment by renatocason** [comment]
Hi @flytomek ,

Those appear to be root category, and they are not currently supported by the extension.

Can you try changing the filter so that level is greater than zero instead than one, here?
https://github.com/aune-io/magento2-product-grid-category-filter/blob/master/Helper/Categories.php#L47

If that works, it could be easily doable to allow filtering by root category based on a configuration.

Renato

**Comment by flytomek** [comment]
It shows me now available categories:
<img width="308" alt="screenshot 2019-02-04 at 13 05 47" src="https://user-images.githubusercontent.com/37069663/52207429-b8ebe080-287d-11e9-90ea-46fbeb82a66e.png">
But it gives me "0 records found". It seems that all products are attached to "Default category" in product grid:
<img width="1150" alt="screenshot 2019-02-04 at 13 07 54" src="https://user-images.githubusercontent.com/37069663/52207489-ed5f9c80-287d-11e9-80c5-7ee92a006df2.png">
where in fact they are in "test" category:
<img width="1175" alt="screenshot 2019-02-04 at 13 08 32" src="https://user-images.githubusercontent.com/37069663/52207520-023c3000-287e-11e9-86c9-951919faaa28.png">

**Comment by renatocason** [comment]
Hi @flytomek ,

Sorry for the delay. Could you check under _Stores > Configuration > Catalog > Catalog > Product Grid Category Filter_ if _Show anchor categories_ and _Filter by anchor categories_ are set to _Yes_ or _No_?
I did some tests locally, and it works only if those selects are set to _No_. This is because the other option uses the index table using the _Reference Store_ to load and filter the information. Magento supports only one root category per store, hence with that option on you would only see the root category assigned to the reference store.

Renato
